set -g default-terminal "xterm-256color"

set -ga terminal-overrides ",xterm*:Tc"
set -s escape-time 0

bind r source-file ~/.config/tmux/tmux.conf

setw -g mouse on
setw -g pane-base-index 1
set -g base-index 1
set -g renumber-windows on
set -g history-limit 10000

unbind v
bind v copy-mode

set-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind | split-window -h
bind - split-window -v

# status bar
set -g status off
# set -g renumber-windows on
# set -g status-position bot
#
# set -g status-style 'bg=#101010 fg=#ffcfa8'
#
# set-window-option -g window-status-current-style bg=#ffcfa8,fg=#161616,bold
# set -g window-status-current-format " #I #W "
# set -g window-status-format " #I #W "
#
# set -g status-left ""
# set -g status-left-length 0
#
# set -g status-right-length 120
# set -g status-interval 60
# set-option -g status-right "#S #[fg=#ff8080]│#[fg=#ffcfa8] %a %Y-%m-%d %H:%M"
